FROM node:alpine

LABEL version='1.0'
LABEL description='This is a docker image of express server side of CMPT 353 project'

# Set the Working Directory the Containers Terminal
WORKDIR /CMPT353app/client/
# Copy Project Over from this folder to Container folder
COPY . /CMPT353app/client/
#install npm dependencies and dev-dependencies
RUN npm install
## expose port
EXPOSE 8080

CMD ["npm","run", "start"]
